(require 'emacs-core) 
(require 'emacs-editor)      ;; Default editor confs 
(require 'emacs-ido)         ;; Super charges Emacs completion for C-x C-f and more
(require 'emacs-fiplr)       ;; Fiplr file search C-x f (find) C-c r (refresh)
(require 'emacs-sr-speedbar) ;; Project explorer like nerdtree
(require 'emacs-theme)
(require 'emacs-ag)
(require 'emacs-wgrep)
(require 'emacs-autocomplete)
(require 'emacs-flyspell)
(require 'emacs-flymake)
(require 'emacs-highlight-symbol)
(require 'emacs-ruby)
(require 'emacs-javascript)
(require 'emacs-scala)
(require 'emacs-smartparens)
(require 'emacs-yasnippet)
(require 'emacs-web-mode)
(require 'emacs-run-file)
(require 'emacs-move-text)
(require 'emacs-ensime)
(require 'emacs-rainbow-mode)
